(() => {
'use strict';
const STORAGE_KEY='emscodesim-pain-opqrst-v1';
const $=id=>document.getElementById(id);
const cases=[
{title:'Minor ankle injury',description:'A 20-year-old stepped off a curb and reports isolated ankle pain.',finding:'Localized musculoskeletal pain pattern',detail:'O: Began immediately after rolling the ankle 25 minutes ago. P: Worse with weight bearing and movement; improved by keeping it still. Q: Aching with occasional sharp pain. R: Lateral right ankle without radiation. S: 5/10. T: Constant since injury; denies numbness, head strike, or other pain.',normality:'normal',priority:'localized',action:'routine',example:'Patient reports 5/10 aching right lateral ankle pain with occasional sharp pain after inversion injury approximately 25 minutes prior. Pain worsens with weight bearing and movement and improves with immobilization. Pain is localized without radiation. Denies numbness, head strike, or additional pain. Distal circulation, motor, and sensation reassessed.'},
{title:'Exertional chest pressure',description:'A 64-year-old developed chest discomfort while carrying boxes upstairs.',finding:'Concerning cardiac-type pain pattern',detail:'O: Began 20 minutes ago during exertion. P: Improved slightly with rest; not reproduced by palpation. Q: Heavy pressure. R: Substernal, radiating to left arm and jaw. S: 8/10. T: Constant. Associated nausea and diaphoresis.',normality:'not-normal',priority:'exertional',action:'cardiac',example:'Patient reports 8/10 constant substernal pressure radiating to the left arm and jaw, beginning during exertion approximately 20 minutes prior. Discomfort improved slightly with rest and is not reproducible with palpation. Associated nausea and diaphoresis present. Patient treated as potentially serious chest pain with expedited transport and serial reassessment.'},
{title:'Sudden severe headache',description:'A 48-year-old developed an abrupt severe headache while lifting a heavy object.',finding:'Sudden maximal-onset headache',detail:'O: Instant onset 10 minutes ago, maximal at start. P: No relief with rest; light worsens discomfort. Q: Explosive, “worst headache of my life.” R: Diffuse head and upper neck. S: 10/10. T: Constant. Associated vomiting and new difficulty speaking.',normality:'not-normal',priority:'sudden',action:'neuro',example:'Patient reports sudden-onset 10/10 explosive diffuse headache with upper-neck pain, maximal immediately at onset approximately 10 minutes prior while lifting. Pain is constant and worsened by light. Associated vomiting and new speech difficulty noted. Focused neurologic assessment performed and rapid transport initiated.'},
{title:'Pleuritic chest pain',description:'A 35-year-old reports sharp right-sided chest pain and shortness of breath.',finding:'Concerning pleuritic pain with respiratory symptoms',detail:'O: Began suddenly 30 minutes ago at rest. P: Worse with deep inspiration and coughing; no relief with position. Q: Sharp and stabbing. R: Right lateral chest, no radiation. S: 7/10. T: Constant. Associated shortness of breath and anxiety.',normality:'not-normal',priority:'pleuritic',action:'respiratory',example:'Patient reports 7/10 sharp, stabbing right lateral chest pain beginning suddenly at rest approximately 30 minutes prior. Pain is constant and worsens with deep inspiration and coughing without radiation. Associated shortness of breath and anxiety present. ABCs, oxygenation, and ventilation reassessed with prompt transport.'},
{title:'Right lower abdominal pain',description:'A 29-year-old reports worsening abdominal pain with nausea.',finding:'Concerning focal abdominal pain pattern',detail:'O: Gradual onset yesterday, worsening over 12 hours. P: Worse with movement and palpation; little relief when still. Q: Initially dull, now sharp. R: Began near umbilicus and moved to right lower quadrant. S: 7/10. T: Constant and worsening. Associated nausea and decreased appetite.',normality:'not-normal',priority:'abdominal',action:'abdominal-care',example:'Patient reports 7/10 constant, worsening right lower-quadrant abdominal pain. Pain began near the umbilicus approximately 12 hours prior and migrated to the right lower quadrant. Pain is now sharp, worsens with movement and palpation, and is associated with nausea and decreased appetite. Patient monitored for shock, kept NPO, and transported.'},
{title:'Pelvic pain after collision',description:'A restrained driver reports severe pelvic pain after a high-speed motor-vehicle collision.',finding:'Pain associated with significant traumatic mechanism',detail:'O: Immediate onset at impact 15 minutes ago. P: Worse with movement; no relief. Q: Deep, severe pressure. R: Pelvis and lower abdomen without leg radiation. S: 9/10. T: Constant. Associated dizziness; pelvis appears unstable on initial assessment.',normality:'not-normal',priority:'trauma',action:'trauma-care',example:'Patient reports 9/10 constant deep pelvic and lower-abdominal pressure beginning immediately after high-speed collision approximately 15 minutes prior. Pain worsens with movement and does not radiate. Dizziness and pelvic instability noted. Trauma priorities addressed, movement minimized, distal neurovascular status reassessed, and rapid transport initiated.'}
];
const state={current:null,revealed:false,complete:{how:false,why:false,practice:false}};
function load(){try{Object.assign(state.complete,JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'));}catch(_){}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.complete));}
function updateProgress(){const n=Object.values(state.complete).filter(Boolean).length;$('progressText').textContent=`${n} of 3 lessons complete`;$('progressBar').style.width=`${n/3*100}%`;document.querySelectorAll('[data-complete]').forEach(b=>{const d=state.complete[b.dataset.complete];b.classList.toggle('is-complete',d);b.textContent=d?'Completed ✓':`Mark ${b.dataset.complete.toUpperCase()} complete`;});}
function switchPanel(id){document.querySelectorAll('.lesson-panel').forEach(p=>{const a=p.id===id;p.hidden=!a;p.classList.toggle('is-active',a);});document.querySelectorAll('.lesson-tab').forEach(b=>b.classList.toggle('is-active',b.dataset.panel===id));}
function newCase(){let next;do{next=cases[Math.floor(Math.random()*cases.length)];}while(cases.length>1&&next===state.current);state.current=next;state.revealed=false;$('caseTitle').textContent=next.title;$('caseDescription').textContent=next.description;$('findingBox').hidden=true;$('resultsPanel').hidden=true;$('painForm').reset();}
document.querySelectorAll('.lesson-tab').forEach(b=>b.addEventListener('click',()=>switchPanel(b.dataset.panel)));
document.querySelectorAll('[data-complete]').forEach(b=>b.addEventListener('click',()=>{state.complete[b.dataset.complete]=true;save();updateProgress();}));
$('checkWhy').addEventListener('click',()=>{const v=document.querySelector('input[name="whyQuestion"]:checked')?.value;$('whyFeedback').textContent=v==='objective'?'Correct. It records the patient’s words, location, radiation, severity, onset, and context.':'Use objective details instead of a vague label such as “severe pain.”';});
$('newCase').addEventListener('click',newCase);$('tryAnother').addEventListener('click',()=>{newCase();$('practicePanel').scrollIntoView({behavior:'smooth'});});
$('performAssessment').addEventListener('click',()=>{state.revealed=true;$('findingText').textContent=state.current.finding;$('findingDetail').textContent=state.current.detail;$('findingBox').hidden=false;$('findingBox').scrollIntoView({behavior:'smooth',block:'nearest'});});
$('painForm').addEventListener('submit',e=>{e.preventDefault();if(!state.revealed){alert('Ask the OPQRST questions before grading the case.');return;}const normality=document.querySelector('input[name="normality"]:checked')?.value||'';const priority=$('prioritySelect').value;const action=$('actionSelect').value;const pcr=$('pcrText').value.trim();let score=0;const feedback=[];
if(normality===state.current.normality){score++;feedback.push('Correctly classified the pain pattern as expected or concerning.');}else feedback.push(`This case should be classified as ${state.current.normality==='normal'?'normal/expected':'not normal/concerning'}.`);
if(priority===state.current.priority){score++;feedback.push('Identified the most clinically important pain feature.');}else feedback.push('Reconsider onset, quality, radiation, associated symptoms, and mechanism.');
if(action===state.current.action){score++;feedback.push('Selected the best immediate EMT priority.');}else feedback.push('Choose the action that addresses the highest-risk pattern while continuing ABC reassessment.');
const terms=['onset','began','worse','better','sharp','pressure','aching','radiat','10','constant','intermittent','denies','associated','reassess'];const hits=terms.filter(t=>pcr.toLowerCase().includes(t)).length;if(pcr.length>=100&&hits>=6){score++;feedback.push('Documentation captures useful OPQRST details and associated findings.');}else feedback.push('Include onset, provoking/relieving factors, quality, region/radiation, severity, time course, associated symptoms, and reassessment.');
$('scoreText').textContent=`${score}/4`;$('feedbackList').innerHTML=feedback.map(x=>`<li>${x}</li>`).join('');$('examplePCR').textContent=state.current.example;$('resultsPanel').hidden=false;$('resultsPanel').scrollIntoView({behavior:'smooth',block:'start'});if(score===4){state.complete.practice=true;save();updateProgress();}});
load();updateProgress();newCase();
})();