(() => {
  'use strict';
  const STORAGE_KEY = 'emscodesim-sample-history-v1';
  const $ = id => document.getElementById(id);
  const cases = [
    {title:'Uncomplicated ankle injury',description:'A 24-year-old twisted an ankle stepping off a curb and has isolated pain without other complaints.',finding:'No major high-risk history item identified',detail:'S: Right ankle pain and swelling. A: No known allergies. M: Daily multivitamin only. P: No significant history. L: Ate lunch 2 hours ago. E: Inversion injury while stepping off curb; denies head strike or loss of consciousness.',normality:'normal',priority:'none',action:'continue',example:'SAMPLE obtained: patient reports isolated right ankle pain and swelling after inversion injury. Denies additional symptoms, head strike, or loss of consciousness. NKDA. Takes daily multivitamin only. Denies significant medical history. Last oral intake approximately 2 hours prior. Assessment and routine monitoring continued.'},
    {title:'Allergic reaction',description:'A 31-year-old developed itching, hives, and throat tightness shortly after eating at a restaurant.',finding:'High-risk allergy history',detail:'S: Generalized itching, hives, throat tightness. A: Known peanut allergy causing prior facial swelling. M: Carries epinephrine auto-injector but has not used it. P: Prior anaphylaxis. L: Meal 20 minutes ago. E: Symptoms began minutes after eating dessert containing nuts.',normality:'not-normal',priority:'allergy',action:'allergy-care',example:'SAMPLE obtained: patient reports generalized itching, hives, and throat tightness beginning minutes after eating dessert containing nuts. History of peanut allergy with prior facial swelling/anaphylaxis. Carries epinephrine auto-injector but had not used it before EMS arrival. Last oral intake approximately 20 minutes prior. Airway and breathing reassessed and anaphylaxis care initiated per protocol.'},
    {title:'Fall on anticoagulant',description:'A 78-year-old fell in the bathroom and struck the back of the head. The patient denies loss of consciousness.',finding:'High-risk medication history',detail:'S: Mild headache and dizziness. A: Penicillin causes rash. M: Apixaban for atrial fibrillation. P: Atrial fibrillation and hypertension. L: Breakfast 3 hours ago. E: Slipped on wet floor and struck occiput.',normality:'not-normal',priority:'medication',action:'bleeding-risk',example:'SAMPLE obtained: patient reports headache and dizziness after ground-level fall with occipital head strike. Denies loss of consciousness. Allergy to penicillin causes rash. Takes apixaban for atrial fibrillation and antihypertensive medication. Last oral intake approximately 3 hours prior. Anticoagulant use identified as increased bleeding risk; neurologic status monitored and transport prioritized.'},
    {title:'Diabetic confusion',description:'A 56-year-old with diabetes is confused, diaphoretic, and unable to answer questions normally.',finding:'Pertinent history and missed intake raise concern for hypoglycemia',detail:'S: Confusion, weakness, diaphoresis. A: No known allergies. M: Insulin; usual morning dose taken. P: Type 1 diabetes. L: No food since the previous evening. E: Became confused at work after skipping breakfast.',normality:'not-normal',priority:'intake',action:'glucose',example:'SAMPLE obtained from patient and coworker: patient became confused and diaphoretic after skipping breakfast. History of type 1 diabetes; took usual morning insulin. NKDA. No oral intake since previous evening. Blood glucose assessment initiated and treatment provided per findings.'},
    {title:'Possible opioid effect',description:'A 42-year-old is drowsy with slow respirations after taking pain medication for a recent injury.',finding:'Medication history suggests possible overdose or adverse effect',detail:'S: Drowsiness and slowed breathing. A: No known allergies. M: Oxycodone prescribed after surgery; family reports several tablets may be missing. P: Recent orthopedic surgery. L: Small meal 5 hours ago. E: Became progressively difficult to wake after taking medication.',normality:'not-normal',priority:'medication',action:'overdose',example:'SAMPLE obtained primarily from family due to altered mental status. Patient became progressively difficult to wake after taking prescribed oxycodone. Family reports several tablets may be missing. NKDA. Recent orthopedic surgery. Last known oral intake approximately 5 hours prior. Possible medication effect or overdose considered; airway and ventilation supported and patient reassessed.'},
    {title:'Exertional chest discomfort',description:'A 63-year-old developed pressure-like chest discomfort while carrying boxes upstairs.',finding:'Events and medical history increase concern for a serious cardiac cause',detail:'S: Substernal pressure with nausea. A: Sulfa drugs cause hives. M: Aspirin, metoprolol, nitroglycerin. P: Prior myocardial infarction and hypertension. L: Breakfast 4 hours ago. E: Symptoms began during exertion and improved slightly with rest.',normality:'not-normal',priority:'events',action:'rapid-transport',example:'SAMPLE obtained: patient reports substernal pressure and nausea beginning during exertion while carrying boxes. Allergy to sulfa drugs causes hives. Medications include aspirin, metoprolol, and prescribed nitroglycerin. History of prior myocardial infarction and hypertension. Last oral intake approximately 4 hours prior. Cardiac concern recognized; rapid transport and continuous reassessment initiated.'}
  ];
  const state={current:null,revealed:false,complete:{how:false,why:false,practice:false}};
  function load(){try{Object.assign(state.complete,JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'));}catch(_){} }
  function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.complete));}
  function updateProgress(){const n=Object.values(state.complete).filter(Boolean).length;$('progressText').textContent=`${n} of 3 lessons complete`;$('progressBar').style.width=`${(n/3)*100}%`;document.querySelectorAll('[data-complete]').forEach(b=>{const done=state.complete[b.dataset.complete];b.classList.toggle('is-complete',done);b.textContent=done?'Completed ✓':`Mark ${b.dataset.complete.toUpperCase()} complete`;});}
  function switchPanel(id){document.querySelectorAll('.lesson-panel').forEach(p=>{const active=p.id===id;p.hidden=!active;p.classList.toggle('is-active',active);});document.querySelectorAll('.lesson-tab').forEach(b=>b.classList.toggle('is-active',b.dataset.panel===id));}
  function newCase(){let next = window.EMSCodeSimScenarioRuntime?.chooseCase('sample', cases, state.current) || cases[0];state.current=next;state.revealed=false;$('caseTitle').textContent=next.title;$('caseDescription').textContent=next.description;$('findingBox').hidden=true;$('resultsPanel').hidden=true;$('sampleForm').reset();}
  document.querySelectorAll('.lesson-tab').forEach(b=>b.addEventListener('click',()=>switchPanel(b.dataset.panel)));
  document.querySelectorAll('[data-complete]').forEach(b=>b.addEventListener('click',()=>{state.complete[b.dataset.complete]=true;save();updateProgress();}));
  $('checkWhy').addEventListener('click',()=>{const value=document.querySelector('input[name="whyQuestion"]:checked')?.value;$('whyFeedback').textContent=value==='reaction'?'Correct. The reaction helps determine severity and clinical significance.':'Ask what reaction occurs. The allergy name alone does not describe the risk.';});
  $('newCase').addEventListener('click',newCase);
  $('tryAnother').addEventListener('click',()=>{newCase();$('practicePanel').scrollIntoView({behavior:'smooth'});});
  $('performAssessment').addEventListener('click',()=>{state.revealed=true;$('findingText').textContent=state.current.finding;$('findingDetail').textContent=state.current.detail;$('findingBox').hidden=false;$('findingBox').scrollIntoView({behavior:'smooth',block:'nearest'});});
  $('sampleForm').addEventListener('submit',e=>{e.preventDefault();if(!state.revealed){alert('Ask the SAMPLE questions before grading the case.');return;}const normality=document.querySelector('input[name="normality"]:checked')?.value||'';const priority=$('prioritySelect').value;const action=$('actionSelect').value;const pcr=$('pcrText').value.trim();let score=0;const feedback=[];
    if(normality===state.current.normality){score++;feedback.push('Correctly identified whether the history contains an important abnormal or high-risk finding.');}else feedback.push(`Review the history significance: this case ${state.current.normality==='normal'?'does not contain':'does contain'} a major high-risk finding.`);
    if(priority===state.current.priority){score++;feedback.push('Correctly identified the most important SAMPLE item.');}else feedback.push('Reconsider which answer most directly changes risk, treatment, or transport priority.');
    if(action===state.current.action){score++;feedback.push('Selected the best immediate EMT action.');}else feedback.push('Use the history to guide the next assessment or treatment while continuing ABC reassessment.');
    const terms=['allerg','reaction','medication','takes','history','intake','ate','event','began','denies','reports','prior','last','sAMPLE'.toLowerCase()];const hits=terms.filter(t=>pcr.toLowerCase().includes(t)).length;if(pcr.length>=90&&hits>=5){score++;feedback.push('Documentation includes useful pertinent positives and negatives.');}else feedback.push('Document the relevant SAMPLE answers, allergy reaction, medication details, timing, events, and important negatives.');
    $('scoreText').textContent=`Score: ${score} of 4`;$('feedbackList').innerHTML=feedback.map(x=>`<li>${x}</li>`).join('');$('examplePCR').textContent=state.current.example;
    window.EMSCodeSimAssessmentIntegration?.saveAssessment({
      assessment: 'sample_history',
      label: 'Sample History',
      scenarioTitle: state.current.title || '',
      finding: state.current.finding || '',
      details: state.current.detail || state.current.description || '',
      normality,
      expectedNormality: state.current.normality,
      interpretation: typeof priority !== 'undefined' ? priority : '',
      action: typeof action !== 'undefined' ? action : '',
      documentation: pcr,
      score,
      maxScore: 4
    });
$('resultsPanel').hidden=false;$('resultsPanel').scrollIntoView({behavior:'smooth',block:'start'});if(score===4){state.complete.practice=true;save();updateProgress();}
  });
  load();updateProgress();newCase();
})();
