(()=>{'use strict';
const FLOWS={
 asthma:[['Airway assessment','/vitals/airway-assessment.html'],['Breathing quality','/vitals/breathing-assessment.html'],['Pulse and SpO₂','/vitals/pulse.html'],['SAMPLE history','/vitals/sample-history.html'],['Clinical impression','/vitals/clinical-impression.html'],['Treatment and reassessment','/vitals/treatment-reassessment.html'],['PCR and handoff','/vitals/pcr-handoff.html'],['Scenario debrief','/vitals/scenario-debrief.html']],
 stroke:[['Airway assessment','/vitals/airway-assessment.html'],['Vital signs','/vitals/full-vitals-set.html'],['Motor and sensory','/vitals/motor-sensory-assessment.html'],['Blood glucose','/vitals/bgl.html'],['SAMPLE history','/vitals/sample-history.html'],['Clinical impression','/vitals/clinical-impression.html'],['PCR and handoff','/vitals/pcr-handoff.html'],['Scenario debrief','/vitals/scenario-debrief.html']],
 hypoglycemia:[['Airway assessment','/vitals/airway-assessment.html'],['AVPU and orientation','/vitals/avpu.html'],['Blood glucose','/vitals/bgl.html'],['SAMPLE history','/vitals/sample-history.html'],['Clinical impression','/vitals/clinical-impression.html'],['Treatment and reassessment','/vitals/treatment-reassessment.html'],['PCR and handoff','/vitals/pcr-handoff.html'],['Scenario debrief','/vitals/scenario-debrief.html']],
 trauma:[['Airway assessment','/vitals/airway-assessment.html'],['Breathing quality','/vitals/breathing-assessment.html'],['Chest assessment','/vitals/chest-assessment.html'],['Trauma head-to-toe','/vitals/trauma-assessment.html'],['Abdominal assessment','/vitals/abdominal-assessment.html'],['Perfusion assessment','/vitals/perfusion-assessment.html'],['PCR and handoff','/vitals/pcr-handoff.html'],['Scenario debrief','/vitals/scenario-debrief.html']],
 pediatric:[['Pediatric Assessment Triangle','/vitals/pediatric-assessment-triangle.html'],['Airway assessment','/vitals/airway-assessment.html'],['Breathing quality','/vitals/breathing-assessment.html'],['Perfusion assessment','/vitals/perfusion-assessment.html'],['SAMPLE history','/vitals/sample-history.html'],['Treatment and reassessment','/vitals/treatment-reassessment.html'],['PCR and handoff','/vitals/pcr-handoff.html'],['Scenario debrief','/vitals/scenario-debrief.html']]
};
const path=()=>location.pathname.replace(/\/+$/,'')||'/';
function record(){try{return window.EMSCodeSimPatientRecord?.active?.()||null}catch{return null}}
function flow(){const r=record();return r?FLOWS[r.scenarioId]||FLOWS[r.id]||[]:[]}
function scenarioStateKey(r){return `emscodesim_scenario_${r.scenarioId||r.id}`}
function markCurrentDone(){const r=record(),f=flow();if(!r||!f.length)return;const i=f.findIndex(x=>x[1]===path());if(i<0||i>=f.length-1)return;let s={done:[],complete:false};try{s=JSON.parse(localStorage.getItem(scenarioStateKey(r)))||s}catch{}if(!s.done.includes(i))s.done.push(i);localStorage.setItem(scenarioStateKey(r),JSON.stringify(s));}
function remaining(){const f=flow(),i=f.findIndex(x=>x[1]===path());if(i<0)return f.slice(0,3);return f.slice(i+1).filter(x=>x[1]!==path());}
function ensure(){let host=document.getElementById('emsScenarioFlow');if(host)return host;host=document.createElement('aside');host.id='emsScenarioFlow';host.hidden=true;host.setAttribute('aria-live','polite');host.innerHTML='<div class="esf-card"><div class="esf-top"><div><p class="esf-eyebrow">Assessment saved</p><h2 id="esfTitle">Continue the patient assessment</h2><p id="esfText"></p></div><button class="esf-close" type="button" aria-label="Close">×</button></div><div class="esf-actions" id="esfActions"></div><div class="esf-progress" id="esfProgress"></div></div>';document.body.appendChild(host);host.querySelector('.esf-close').addEventListener('click',()=>host.hidden=true);return host;}
function show(){const r=record();if(!r)return;markCurrentDone();const host=ensure(),list=remaining(),actions=host.querySelector('#esfActions');actions.innerHTML='';host.querySelector('#esfText').textContent=list.length?`Keep working with ${r.patient||'the same patient'}. Choose the recommended next step or another remaining assessment.`:'All required patient-care steps are complete. Review the scenario debrief.';
 const recommended=list[0]||['Scenario debrief','/vitals/scenario-debrief.html'];const a=document.createElement('a');a.className='esf-primary';a.href=recommended[1]+'?mode=scenario';a.textContent=`Continue: ${recommended[0]}`;actions.appendChild(a);
 list.slice(1,4).forEach(item=>{const x=document.createElement('a');x.className='esf-choice';x.href=item[1]+'?mode=scenario';x.textContent=item[0];actions.appendChild(x)});
 const rec=document.createElement('a');rec.className='esf-record';rec.href='/vitals/patient-record.html?mode=scenario';rec.textContent='View patient findings';actions.appendChild(rec);
 const total=flow().length-1;let s={done:[]};try{s=JSON.parse(localStorage.getItem(scenarioStateKey(r)))||s}catch{}host.querySelector('#esfProgress').textContent=`${Math.min(s.done.length,total)} of ${total} scenario steps completed`;host.hidden=false;host.scrollIntoView({behavior:'smooth',block:'nearest'});
}
window.addEventListener('emscodesim:assessment-saved',show);window.addEventListener('emscodesim:care-step-saved',show);
window.EMSCodeSimScenarioFlow={show,markCurrentDone,flow};
})();
