(()=>{'use strict';
const FLOWS={
 asthma:[['Airway assessment','/vitals/airway-assessment.html'],['Breathing quality','/vitals/breathing-assessment.html'],['Respiratory rate','/vitals/respiratory-rate-scenario.html'],['Breath sounds','/vitals/breath-sounds-scenario.html'],['Pulse','/vitals/pulse-scenario.html'],['Blood pressure','/vitals/bp-scenario.html'],['SpO₂','/vitals/pulse-ox-scenario.html'],['SAMPLE history','/vitals/sample-history.html'],['Clinical impression','/vitals/clinical-impression.html'],['Treatment and reassessment','/vitals/treatment-reassessment.html'],['PCR and handoff','/vitals/pcr-handoff.html'],['Scenario debrief','/vitals/scenario-debrief.html']],
 stroke:[['Airway assessment','/vitals/airway-assessment.html'],['Pulse','/vitals/pulse-scenario.html'],['Blood pressure','/vitals/bp-scenario.html'],['Respiratory rate','/vitals/respiratory-rate-scenario.html'],['SpO₂','/vitals/pulse-ox-scenario.html'],['Breath sounds','/vitals/breath-sounds-scenario.html'],['Motor and sensory','/vitals/motor-sensory-assessment.html'],['Blood glucose','/vitals/bgl-scenario.html'],['SAMPLE history','/vitals/sample-history.html'],['Clinical impression','/vitals/clinical-impression.html'],['PCR and handoff','/vitals/pcr-handoff.html'],['Scenario debrief','/vitals/scenario-debrief.html']],
 hypoglycemia:[['Airway assessment','/vitals/airway-assessment.html'],['AVPU and orientation','/vitals/avpu-scenario.html'],['Pulse','/vitals/pulse-scenario.html'],['Blood pressure','/vitals/bp-scenario.html'],['Respiratory rate','/vitals/respiratory-rate-scenario.html'],['SpO₂','/vitals/pulse-ox-scenario.html'],['Blood glucose','/vitals/bgl-scenario.html'],['SAMPLE history','/vitals/sample-history.html'],['Clinical impression','/vitals/clinical-impression.html'],['Treatment and reassessment','/vitals/treatment-reassessment.html'],['PCR and handoff','/vitals/pcr-handoff.html'],['Scenario debrief','/vitals/scenario-debrief.html']],
 trauma:[['Airway assessment','/vitals/airway-assessment.html'],['Breathing quality','/vitals/breathing-assessment.html'],['Respiratory rate','/vitals/respiratory-rate-scenario.html'],['Breath sounds','/vitals/breath-sounds-scenario.html'],['Pulse','/vitals/pulse-scenario.html'],['Blood pressure','/vitals/bp-scenario.html'],['SpO₂','/vitals/pulse-ox-scenario.html'],['Chest assessment','/vitals/chest-assessment.html'],['Trauma head-to-toe','/vitals/trauma-assessment.html'],['Abdominal assessment','/vitals/abdominal-assessment.html'],['Perfusion assessment','/vitals/perfusion-assessment.html'],['PCR and handoff','/vitals/pcr-handoff.html'],['Scenario debrief','/vitals/scenario-debrief.html']],
 pediatric:[['Pediatric Assessment Triangle','/vitals/pediatric-assessment-triangle.html'],['Airway assessment','/vitals/airway-assessment.html'],['Breathing quality','/vitals/breathing-assessment.html'],['Respiratory rate','/vitals/respiratory-rate-scenario.html'],['Breath sounds','/vitals/breath-sounds-scenario.html'],['Pulse','/vitals/pulse-scenario.html'],['Blood pressure','/vitals/bp-scenario.html'],['SpO₂','/vitals/pulse-ox-scenario.html'],['Perfusion assessment','/vitals/perfusion-assessment.html'],['SAMPLE history','/vitals/sample-history.html'],['Treatment and reassessment','/vitals/treatment-reassessment.html'],['PCR and handoff','/vitals/pcr-handoff.html'],['Scenario debrief','/vitals/scenario-debrief.html']]
};
const path=()=>location.pathname.replace(/\/+$/,'')||'/';
function record(){try{return window.EMSCodeSimPatientRecord?.active?.()||null}catch{return null}}
function flow(){const r=record();return r?FLOWS[r.scenarioId]||FLOWS[r.id]||[]:[]}
function scenarioStateKey(r){return `emscodesim_scenario_${r.scenarioId||r.id}`}
function state(r){let s={done:[],complete:false};try{s=JSON.parse(localStorage.getItem(scenarioStateKey(r)))||s}catch{};if(!Array.isArray(s.done))s.done=[];return s}
function markCurrentDone(){const r=record(),f=flow();if(!r||!f.length)return;const i=f.findIndex(x=>x[1]===path());if(i<0)return;const s=state(r);if(!s.done.includes(i))s.done.push(i);localStorage.setItem(scenarioStateKey(r),JSON.stringify(s));}
function remaining(){const r=record(),f=flow();if(!r)return[];const s=state(r);const current=f.findIndex(x=>x[1]===path());return f.filter((x,i)=>i!==current&&!s.done.includes(i));}
function urlFor(item){const r=record();const id=encodeURIComponent(r?.scenarioId||r?.id||'');return `${item[1]}?mode=scenario&resume=1${id?`&case=${id}`:''}`}
function ensure(){let host=document.getElementById('emsScenarioFlow');if(host)return host;host=document.createElement('aside');host.id='emsScenarioFlow';host.hidden=true;host.setAttribute('aria-live','assertive');host.innerHTML='<div class="esf-card"><div class="esf-top"><div><p class="esf-eyebrow">Step complete</p><h2 id="esfTitle">Continuing the scenario</h2><p id="esfText"></p></div><button class="esf-close" type="button" aria-label="Stay on this page">×</button></div><div class="esf-actions" id="esfActions"></div><div class="esf-progress" id="esfProgress"></div></div>';document.body.appendChild(host);host.querySelector('.esf-close').addEventListener('click',()=>{clearTimeout(host._advanceTimer);host.hidden=true});return host;}
function show(){const r=record();if(!r)return;markCurrentDone();const host=ensure();clearTimeout(host._advanceTimer);const list=remaining(),actions=host.querySelector('#esfActions');actions.innerHTML='';const recommended=list[0]||['Scenario debrief','/vitals/scenario-debrief.html'];let seconds=4;
 host.querySelector('#esfText').textContent=`${r.patient||'The patient'} remains active. Continuing to ${recommended[0]} in ${seconds} seconds.`;
 const a=document.createElement('a');a.className='esf-primary';a.href=urlFor(recommended);a.textContent=`Continue now: ${recommended[0]}`;actions.appendChild(a);
 list.slice(1,4).forEach(item=>{const x=document.createElement('a');x.className='esf-choice';x.href=urlFor(item);x.textContent=item[0];x.addEventListener('click',()=>clearTimeout(host._advanceTimer));actions.appendChild(x)});
 const rec=document.createElement('a');rec.className='esf-record';rec.href='/vitals/patient-record.html?mode=scenario&resume=1';rec.textContent='View patient findings';rec.addEventListener('click',()=>clearTimeout(host._advanceTimer));actions.appendChild(rec);
 const total=flow().length;const s=state(r);host.querySelector('#esfProgress').textContent=`${Math.min(s.done.length,total)} of ${total} scenario steps completed`;host.hidden=false;
 function tick(){seconds--;if(seconds<=0){location.href=urlFor(recommended);return}host.querySelector('#esfText').textContent=`${r.patient||'The patient'} remains active. Continuing to ${recommended[0]} in ${seconds} seconds.`;host._advanceTimer=setTimeout(tick,1000)}
 host._advanceTimer=setTimeout(tick,1000);host.scrollIntoView({behavior:'smooth',block:'nearest'});
}
window.addEventListener('emscodesim:assessment-saved',()=>show());window.addEventListener('emscodesim:care-step-saved',()=>show());
window.EMSCodeSimScenarioFlow={show,markCurrentDone,flow};
})();
