(()=>{'use strict';
const CASES={
 asthma:{title:'Respiratory Distress',visible:'Sitting upright, anxious, speaking in short sentences',image:'/vitals/assets/scenario-patient-adult-v3.png',assess:[['General appearance','Observe posture, speech, distress, and interaction.','Appears anxious; sitting upright; speaking in short sentences'],['Work of breathing','Watch the chest and neck for effort.','Accessory muscle use with increased work of breathing'],['Breath sounds','Listen to all lung fields.','Expiratory wheezes bilaterally','/vitals/breath-sounds-scenario.html'],['Skin','Inspect color and moisture; assess temperature.','Warm, pink, mildly diaphoretic','/vitals/skin-scenario.html']],treat:[['Position of comfort','Allow the patient to remain upright.','Did the patient tolerate the position?'],['Oxygen','Choose an oxygen device appropriate to the patient.','Which device did you select?'],['Assist inhaler / albuterol','Confirm indications and medication rights.','Did you verify the medication, dose, and expiration?']]},
 stroke:{title:'Possible Acute Stroke',visible:'Awake with abnormal speech and right-sided weakness',image:'/vitals/assets/scenario-patient-adult-v3.png',assess:[['Facial movement','Ask the patient to smile.','Facial asymmetry is present'],['Arm drift','Ask the patient to hold both arms out.','Right arm drift and weakness'],['Speech','Ask the patient to repeat a simple sentence.','Speech is slurred and difficult to understand'],['Pupils','Inspect and test both pupils.','3 mm, equal and reactive','/vitals/pupil-scenario.html']],treat:[['Position and airway protection','Position safely and prepare for vomiting.','Is the airway currently protected?'],['Rapid transport','Select the most appropriate destination and priority.','Was last known well established?']]},
 hypoglycemia:{title:'Altered Mental Status',visible:'Confused, sweaty, and slow to follow commands',image:'/vitals/assets/scenario-patient-adult-v3.png',assess:[['Mental status','Assess AVPU and orientation.','Responds to verbal stimuli; confused','/vitals/avpu-scenario.html'],['Skin','Inspect and feel the skin.','Pale, cool, and diaphoretic','/vitals/skin-scenario.html'],['Stroke screen','Check for focal neurologic deficits.','No focal unilateral deficit identified']],treat:[['Oral glucose','Confirm the patient can swallow and follow commands.','Can this patient safely swallow?'],['Airway support','Prepare suction and airway equipment.','What would make oral glucose unsafe?']]},
 trauma:{title:'Blunt Trauma',visible:'Pale patient with guarded breathing after a collision',image:'/vitals/assets/scenario-patient-adult-v3.png',assess:[['General impression','Look for immediate threats and distress.','Pale, anxious, and in significant pain'],['Chest','Inspect and palpate the chest.','Left chest tenderness with unequal movement'],['Abdomen','Inspect and palpate all quadrants.','Diffuse tenderness with guarding'],['Skin / perfusion','Assess skin and peripheral perfusion.','Pale, cool, clammy; weak radial pulse']],treat:[['Spinal motion restriction','Use only when indicated by the assessment.','What finding supports this decision?'],['Oxygen / ventilation support','Treat hypoxia or inadequate ventilation.','Is breathing adequate or inadequate?'],['Hemorrhage and shock care','Control bleeding and prevent heat loss.','What transport priority is appropriate?']]},
 pediatric:{title:'Sick Pediatric Patient',visible:'Poor interaction with increased work of breathing',image:'/vitals/assets/scenario-patient-pediatric-v3.png',assess:[['Pediatric first look','Assess appearance, breathing, and circulation to skin.','Poor interaction; increased effort; flushed skin'],['Breathing effort','Observe retractions, position, and sounds.','Tachypnea with visible retractions'],['Skin / perfusion','Inspect color and assess capillary refill.','Flushed, hot, mildly mottled']],treat:[['Position and oxygen','Keep the child with caregiver when possible.','Which oxygen method will the child tolerate?'],['Temperature management','Avoid aggressive cooling and reassess.','What is the safest supportive action?']]}
};
const VITALS=[['Blood pressure','/vitals/bp-scenario.html','blood_pressure',24],['Pulse','/vitals/pulse-scenario.html','pulse',15],['Respirations','/vitals/respiratory-rate-scenario.html','respirations',20],['Breath sounds','/vitals/breath-sounds-scenario.html','breath_sounds',22],['Blood glucose','/vitals/bgl-scenario.html','blood_glucose',28],['SpO₂','/vitals/pulse-ox-scenario.html','spo2',12],['Temperature','/vitals/temperature-scenario.html','temperature',18],['Pupils','/vitals/pupil-scenario.html','pupils',12],['Skin signs','/vitals/skin-scenario.html','skin',10],['Mental status','/vitals/avpu-scenario.html','mental_status',8]];
const TITLES={vitalsPanel:'Vitals',assessmentPanel:'Assessment',treatmentPanel:'Treatment',findingsPanel:'Findings'};
const params=new URLSearchParams(location.search);const id=params.get('case')||window.EMSCodeSimPatientRecord?.active?.()?.scenarioId||'asthma';const scenario=CASES[id]||CASES.asthma;let seconds=0;let activeFocus=null;
const $=x=>document.getElementById(x);function record(){return window.EMSCodeSimPatientRecord?.active?.()}function profile(){return window.EMSCodeSimScenarioRuntime?.profile?.()}function toast(msg){$('toast').textContent=msg;$('toast').hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').hidden=true,2500)}
function setPatientImage(img,path){if(!img)return;img.onerror=()=>{img.onerror=null;img.src='/vitals/assets/scenario-patient-adult-v3.png';img.classList.add('image-fallback')};img.src=path;img.hidden=false}
function ensureRecord(){if(record()?.scenarioId===id)return;window.EMSCodeSimPatientRecord?.create?.({id,title:scenario.title,patient:id==='pediatric'?'3-year-old child':'Adult patient',dispatch:scenario.title,scene:'Active scene',goal:'Assess, treat, and reassess'})}
function labelFor(k){return window.EMSCodeSimPatientRecord?.labelFor?.(k)||k.replace(/^treatment_\d+$/,'Treatment').replace(/_/g,' ')}
function valueFor(k){return window.EMSCodeSimScenarioRuntime?.formatVital?.(k)||'Obtained'}
function addFinding(k,v,source='assessment'){const normality=window.EMSCodeSimScenarioRuntime?.classifyFinding?.(k,v)||'';window.EMSCodeSimPatientRecord?.setFinding?.(k,v,{source,normality,status:normality==='normal'?'normal':normality==='not-normal'?'abnormal':''});renderFindings();updateCounts();toast(`${labelFor(k)} recorded`)}
function existing(k){return Boolean(window.EMSCodeSimPatientRecord?.hasFinding?.(k))}
function buildVitals(){const box=$('vitalTools');box.innerHTML='';VITALS.forEach(([name,url,key,delay])=>{const d=document.createElement('article');d.className=`tool${existing(key)?' done':''}`;d.innerHTML=`<div class="tool-head"><div><h3>${name}</h3><p>Perform the skill or delegate it without seeing the answer.</p></div><span class="status-chip ${existing(key)?'done':''}">${existing(key)?'Obtained':'Not taken'}</span></div><div class="tool-actions"><a href="${url}?mode=scenario&case=${encodeURIComponent(id)}&return=${encodeURIComponent(`/vitals/visual-patient.html?case=${id}`)}">Perform</a><button class="partner-action" type="button" ${existing(key)?'disabled':''}>${existing(key)?'Complete':'Assign to partner'}</button></div><div class="assignment-progress" hidden></div>`;const btn=d.querySelector('button'),status=d.querySelector('.assignment-progress');btn.addEventListener('click',()=>{btn.disabled=true;let left=delay;status.hidden=false;status.textContent=`Partner gathering ${name.toLowerCase()}… ${left}s`;const timer=setInterval(()=>{left--;status.textContent=`Partner gathering ${name.toLowerCase()}… ${left}s`;if(left<=0){clearInterval(timer);addFinding(key,valueFor(key),'partner');status.textContent=`Partner reports: ${valueFor(key)}`;btn.textContent='Complete';d.classList.add('done');d.querySelector('.status-chip').textContent='Obtained';d.querySelector('.status-chip').classList.add('done')}},1000)});box.appendChild(d)})}
function openFocus(title,help,finding,key){activeFocus={title,help,finding,key};$('focusTitle').textContent=title;$('focusInstruction').textContent=help;setPatientImage($('focusImage'),scenario.image);$('recordFocus').disabled=true;$('recordFocus').textContent='Observe patient…';$('focusTimer').innerHTML='';void $('focusTimer').offsetWidth;$('assessmentFocus').hidden=false;setTimeout(()=>{if(!activeFocus)return;$('recordFocus').disabled=false;$('recordFocus').textContent='Record observed finding'},4000)}
function buildAssessments(){const box=$('assessmentTools');box.innerHTML='';scenario.assess.forEach(([title,help,finding,url])=>{const key=title.toLowerCase().replace(/\W+/g,'_');const d=document.createElement('article');d.className='assessment-card';d.innerHTML=`<span class="visual-tag">${url?'AUDIO / INTERACTIVE':'VISUAL ASSESSMENT'}</span><h3>${title}</h3><p>${help}</p>${url?`<a class="primary-action" style="display:inline-block;padding:10px 12px;border-radius:10px;text-decoration:none" href="${url}?mode=scenario&case=${encodeURIComponent(id)}&return=${encodeURIComponent(`/vitals/visual-patient.html?case=${id}`)}">Open assessment</a>`:`<button type="button" ${existing(key)?'disabled':''}>${existing(key)?'Finding recorded':'Focus on patient'}</button>`}`;const b=d.querySelector('button');if(b)b.addEventListener('click',()=>openFocus(title,help,finding,key));box.appendChild(d)})}
function buildTreatments(){const box=$('treatmentTools');box.innerHTML='';scenario.treat.forEach(([title,help,question],idx)=>{const key=`treatment_${idx+1}`;const d=document.createElement('article');d.className='treatment-card';d.innerHTML=`<span class="visual-tag">CLINICAL DECISION</span><h3>${title}</h3><p>${help}</p><button type="button" ${existing(key)?'disabled':''}>${existing(key)?'Treatment recorded':'Select treatment'}</button><div class="followup" hidden><label>${question}</label><select><option value="">Choose an answer</option><option>Yes / appropriate</option><option>No / not appropriate</option><option>Need more assessment first</option></select><button type="button" class="primary-action" style="margin-top:8px">Apply and record</button></div>`;const first=d.querySelector('button'),f=d.querySelector('.followup'),save=f.querySelector('button'),sel=f.querySelector('select');first.addEventListener('click',()=>{f.hidden=false;first.hidden=true});save.addEventListener('click',()=>{if(!sel.value){toast('Answer the follow-up question first');return}window.EMSCodeSimPatientRecord?.addTreatment?.({name:title,response:sel.value});addFinding(key,`${title}: ${sel.value}`,'treatment');save.textContent='Treatment recorded';save.disabled=true});box.appendChild(d)})}
function renderFindings(){const list=$('findingList'),items=Object.entries(record()?.findings||{});list.innerHTML='';if(!items.length){list.innerHTML='<li class="empty">No findings yet. Obtain vitals or perform an assessment.</li>';return}items.sort((a,b)=>(a[1].recordedAt||'').localeCompare(b[1].recordedAt||''));items.forEach(([k,o])=>{const li=document.createElement('li');li.innerHTML=`<span>${labelFor(k)}</span><strong>${o.value}</strong>`;list.appendChild(li)})}
function updateCounts(){const findings=record()?.findings||{};const keys=Object.keys(findings);const vitalCount=VITALS.filter(([, ,key])=>keys.includes(key)).length;const treatmentCount=keys.filter(k=>k.startsWith('treatment_')).length;$('vitalCount').textContent=`${vitalCount} / ${VITALS.length}`;$('findingCount').textContent=String(keys.length);$('treatmentCount').textContent=String(treatmentCount);$('findingBadge').hidden=!keys.length;$('findingBadge').textContent=String(keys.length)}
function openSheet(panelId){document.querySelectorAll('.vp-panel').forEach(p=>p.hidden=p.id!==panelId);document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.panel===panelId));$('sheetTitle').textContent=TITLES[panelId];$('actionSheet').hidden=false;$('sheetBackdrop').hidden=false;document.body.style.overflow='hidden';if(panelId==='findingsPanel')renderFindings()}
function closeSheet(){$('actionSheet').hidden=true;$('sheetBackdrop').hidden=true;document.body.style.overflow='';document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.remove('active'))}
function finishFocus(){if(!activeFocus)return;addFinding(activeFocus.key,activeFocus.finding,'visual assessment');$('assessmentFocus').hidden=true;activeFocus=null;buildAssessments();openSheet('findingsPanel')}
function refreshFromRecord(){buildVitals();buildAssessments();buildTreatments();renderFindings();updateCounts();$('patientLabel').textContent=record()?.patient||'Patient';$('dispatch').textContent=record()?.dispatch||scenario.title;$('scene').textContent=record()?.scene||''}ensureRecord();$('caseTitle').textContent=scenario.title;$('visibleCondition').textContent=scenario.visible;setPatientImage($('patientImage'),scenario.image);setPatientImage($('focusImage'),scenario.image);refreshFromRecord();
document.querySelectorAll('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>openSheet(b.dataset.panel)));$('closeSheet').addEventListener('click',closeSheet);$('sheetBackdrop').addEventListener('click',closeSheet);$('recordFocus').addEventListener('click',finishFocus);$('cancelFocus').addEventListener('click',()=>{$('assessmentFocus').hidden=true;activeFocus=null});$('endScenario').addEventListener('click',()=>{if(confirm('End this scenario and return to the launcher?'))location.href='/vitals/scenario-launcher.html'});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('assessmentFocus').hidden){$('assessmentFocus').hidden=true;activeFocus=null}else closeSheet()}});window.addEventListener('emscodesim:patient-record-updated',refreshFromRecord);window.addEventListener('pageshow',refreshFromRecord);setInterval(()=>{seconds++;$('timer').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`},1000);
})();
