(function(){
'use strict';
const progressKey='emscodesim:emt-prep:progress',planKey='emscodesim:emt-prep:plan';
const moduleKeys=['expectations','terminology','anatomy-physiology','vital-signs','assessment','student-habits'];
const moduleBoxes=[...document.querySelectorAll('[data-prep-module]')],readinessBoxes=[...document.querySelectorAll('[data-prep-readiness]')];
const progressBar=document.getElementById('prepProgressBar'),progressText=document.getElementById('prepProgressText'),progressTrack=document.getElementById('prepProgressTrack'),progressDetail=document.getElementById('prepProgressDetail');
let saved={modules:{},readiness:{}};try{saved=Object.assign(saved,JSON.parse(localStorage.getItem(progressKey)||'{}'));}catch(e){}saved.modules=saved.modules||{};saved.readiness=saved.readiness||{};
function persist(){try{localStorage.setItem(progressKey,JSON.stringify(saved));}catch(e){}}
function updateProgress(){const completed=moduleKeys.filter(k=>saved.modules[k]).length,pct=Math.round(completed/moduleKeys.length*100);if(progressBar)progressBar.style.width=pct+'%';if(progressTrack)progressTrack.setAttribute('aria-valuenow',String(pct));if(progressText)progressText.textContent=completed+' of 6 modules';if(progressDetail)progressDetail.textContent=completed===6?'Foundation program complete. Review weak areas until class begins.':pct+'% complete — progress is saved on this device.';moduleBoxes.forEach(box=>{box.checked=!!saved.modules[box.value];const section=box.closest('.prep-module');if(section)section.classList.toggle('is-complete',box.checked);});document.querySelectorAll('[data-module-card]').forEach(card=>{const done=!!saved.modules[card.dataset.moduleCard];card.classList.toggle('is-complete',done);const status=card.querySelector('[data-module-status]');if(status)status.textContent=done?'Completed on this device':'Not completed yet';});}
moduleBoxes.forEach(box=>{box.checked=!!saved.modules[box.value];box.addEventListener('change',()=>{saved.modules[box.value]=box.checked;persist();updateProgress();});});readinessBoxes.forEach(box=>{box.checked=!!saved.readiness[box.value];box.addEventListener('change',()=>{saved.readiness[box.value]=box.checked;persist();});});
const reset=document.getElementById('resetPrepProgress');if(reset)reset.addEventListener('click',()=>{if(!confirm('Clear all saved EMT Prep progress on this device?'))return;saved={modules:{},readiness:{}};moduleBoxes.concat(readinessBoxes).forEach(b=>b.checked=false);persist();updateProgress();});const printButton=document.getElementById('printPrepPlan');if(printButton)printButton.addEventListener('click',()=>print());updateProgress();
const plans={four:[['Week 1','Program expectations, medical terminology, and directional language.'],['Week 2','Anatomy and physiology: respiratory, cardiovascular, nervous, and musculoskeletal systems.'],['Week 3','Vital-sign foundations and guided simulator practice.'],['Week 4','Patient-assessment preview, communication, study habits, and readiness check.']],six:[['Week 1','EMT-school expectations, time planning, and learning habits.'],['Week 2','Medical word parts, abbreviations, and directional language.'],['Week 3','Respiratory, cardiovascular, and nervous-system foundations.'],['Week 4','Musculoskeletal, integumentary, digestive, endocrine, and urinary foundations.'],['Week 5','Vital signs and guided use of EMSCodeSim practice tools.'],['Week 6','Patient assessment, communication, and final readiness check.']]};
const planContainer=document.getElementById('studyPlan'),planButtons=[...document.querySelectorAll('[data-plan]')];function renderPlan(name){const chosen=plans[name]||plans.four;if(planContainer)planContainer.innerHTML=chosen.map(i=>'<div class="study-week"><strong>'+i[0]+'</strong><p>'+i[1]+'</p></div>').join('');planButtons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.plan===name)));try{localStorage.setItem(planKey,name);}catch(e){}}planButtons.forEach(b=>b.addEventListener('click',()=>renderPlan(b.dataset.plan)));let savedPlan='four';try{savedPlan=localStorage.getItem(planKey)||'four';}catch(e){}if(planContainer)renderPlan(plans[savedPlan]?savedPlan:'four');
const questions=[{term:'Bradycardia',prompt:'What does this term most directly describe?',options:['A slow heart rate','A fast breathing rate','Low blood glucose'],answer:0,explain:'brady- means slow and cardi refers to the heart.'},{term:'Tachypnea',prompt:'What does this term most directly describe?',options:['Painful breathing','A fast breathing rate','Absent breathing'],answer:1,explain:'tachy- means fast and -pnea refers to breathing.'},{term:'Hypoglycemia',prompt:'What does this term most directly describe?',options:['High blood pressure','Low blood glucose','Inflammation of a joint'],answer:1,explain:'hypo- means low, glyc refers to sugar, and -emia refers to a blood condition.'},{term:'Bilateral',prompt:'What does this term mean?',options:['Toward the midline','On both sides','Farther from the trunk'],answer:1,explain:'bi- means two and lateral refers to the side.'},{term:'Dyspnea',prompt:'What does this term most directly describe?',options:['Difficult or uncomfortable breathing','A weak pulse','Loss of sensation'],answer:0,explain:'dys- means difficult, abnormal, or painful and -pnea refers to breathing.'}];
let current=0,score=0,answered=false;const termEl=document.getElementById('termWord'),promptEl=document.getElementById('termPrompt'),optionsEl=document.getElementById('termOptions'),feedbackEl=document.getElementById('termFeedback'),nextEl=document.getElementById('nextTermQuestion'),restartEl=document.getElementById('restartTermDrill');function showQuestion(){answered=false;const q=questions[current];if(termEl)termEl.textContent=q.term;if(promptEl)promptEl.textContent=q.prompt;if(feedbackEl)feedbackEl.textContent='Question '+(current+1)+' of '+questions.length;if(optionsEl){optionsEl.innerHTML='';q.options.forEach((option,index)=>{const b=document.createElement('button');b.type='button';b.className='term-option';b.textContent=option;b.addEventListener('click',()=>answer(index,b));optionsEl.appendChild(b);});}if(nextEl){nextEl.hidden=true;nextEl.textContent=current===questions.length-1?'See score':'Next question';}}
function answer(index,button){if(answered)return;answered=true;const q=questions[current],buttons=[...optionsEl.querySelectorAll('button')];buttons.forEach((item,i)=>{item.disabled=true;if(i===q.answer)item.classList.add('correct');});if(index===q.answer){score++;if(feedbackEl)feedbackEl.textContent='Correct. '+q.explain;}else{button.classList.add('incorrect');if(feedbackEl)feedbackEl.textContent='Not quite. '+q.explain;}if(nextEl)nextEl.hidden=false;}
if(nextEl)nextEl.addEventListener('click',()=>{if(current<questions.length-1){current++;showQuestion();return;}if(termEl)termEl.textContent='Finished';if(promptEl)promptEl.textContent='You scored '+score+' of '+questions.length+'. Review the word parts, then try again later.';if(optionsEl)optionsEl.innerHTML='';if(feedbackEl)feedbackEl.textContent=score>=4?'Strong start for EMT school.':'Use the table above and repeat the drill.';nextEl.hidden=true;if(restartEl)restartEl.hidden=false;});if(restartEl)restartEl.addEventListener('click',()=>{current=0;score=0;restartEl.hidden=true;showQuestion();});if(termEl)showQuestion();
})();