(function(){
  const search=document.getElementById('toolSearch'),category=document.getElementById('toolCategory'),level=document.getElementById('toolLevel'),clear=document.getElementById('clearToolFilters'),summary=document.getElementById('toolSummary');
  const cards=[...document.querySelectorAll('.training-card')];if(!search||!category||!level||!summary)return;
  const params=new URLSearchParams(location.search),skillsMode=params.get('mode')==='skills';
  const skillCategories={Assessment:['Patient Assessment','Trauma Assessment','Neurologic Assessment','Pediatric Assessment','Respiratory'],Vitals:['Vital Signs'],Documentation:['Documentation']};
  const timeByCategory={'Protocol Practice':8,'Patient Assessment':15,'Documentation':15,'Knowledge Review':10,'Vital Signs':5,'Respiratory':8,'Neurologic Assessment':6,'Trauma Assessment':10,'Pediatric Assessment':8,'Medication Safety':8};
  let skillsFocus='';
  [...new Set(cards.map(c=>c.dataset.category))].sort().forEach(v=>category.add(new Option(v,v)));
  [...new Set(cards.map(c=>c.dataset.level))].sort().forEach(v=>level.add(new Option(v,v)));
  cards.forEach(card=>{const details=document.createElement('div');details.className='skills-tool-details';details.innerHTML=`<span>For: ${card.dataset.level}</span><span>${timeByCategory[card.dataset.category]||8} min</span>${Object.values(skillCategories).flat().includes(card.dataset.category)?'<span class="skills-badge">Use in skills session</span>':''}`;const paragraph=card.querySelector('p');if(paragraph)paragraph.before(details)});
  function categoryMatch(card){if(!skillsMode||!skillsFocus)return !skillsMode||Object.values(skillCategories).flat().includes(card.dataset.category);return skillCategories[skillsFocus].includes(card.dataset.category)}
  function update(){const q=search.value.trim().toLowerCase();let visible=0;cards.forEach(c=>{const show=categoryMatch(c)&&(!q||c.dataset.search.includes(q))&&(!category.value||c.dataset.category===category.value)&&(!level.value||c.dataset.level===level.value);c.hidden=!show;if(show)visible++});summary.textContent=`Showing ${visible} of ${cards.length} free training tools.`}
  if(skillsMode){const chipWrap=document.createElement('div');chipWrap.className='skills-mode-chips';chipWrap.setAttribute('aria-label','Skills-session tool categories');const requested=params.get('focus');skillsFocus=requested==='vitals'?'Vitals':requested==='documentation'?'Documentation':'Assessment';chipWrap.innerHTML=Object.keys(skillCategories).map(name=>`<button type="button" data-skills-focus="${name}" class="${name===skillsFocus?'active':''}">${name}</button>`).join('');document.querySelector('.library-controls').before(chipWrap);chipWrap.addEventListener('click',event=>{const button=event.target.closest('[data-skills-focus]');if(!button)return;skillsFocus=button.dataset.skillsFocus;chipWrap.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===button));category.value='';level.value='';update()})}
  [search,category,level].forEach(x=>x.addEventListener(x===search?'input':'change',update));clear.addEventListener('click',()=>{search.value='';category.value='';level.value='';update();search.focus()});update();
})();
