(()=>{'use strict';
const api=window.EMSCodeSimPatientRecord;
const record=api?.active?.();
const $=id=>document.getElementById(id);
if(!record){$('noPatient').hidden=false;return}
$('debrief').hidden=false;
const caseId=record.scenarioId||record.id||'asthma';
$('debriefTitle').textContent=`${record.title||'Patient Scenario'} Debrief`;
$('debriefDispatch').textContent=record.dispatch||'Review the assessment and identify the next best learning step.';
const catalog={
 airway:{label:'Airway',sim:'/vitals/airway-assessment.html',q:'airway assessment'},breathing:{label:'Breathing quality',sim:'/vitals/breathing-assessment.html',q:'work of breathing respiratory assessment'},perfusion:{label:'Circulation and perfusion',sim:'/vitals/perfusion-assessment.html',q:'perfusion circulation skin signs'},pulse:{label:'Pulse',sim:'/vitals/pulse.html',q:'pulse rate rhythm quality'},blood_pressure:{label:'Blood pressure',sim:'/vitals/bp.html',q:'blood pressure'},respirations:{label:'Respiratory rate',sim:'/vitals/respiratory-rate.html',q:'respiratory rate'},spo2:{label:'SpO₂',sim:'/vitals/pulse-ox.html',q:'pulse oximetry SpO2'},breath_sounds:{label:'Breath sounds',sim:'/vitals/breath-sound-simulator.html',q:'breath sounds'},mental_status:{label:'Mental status',sim:'/vitals/avpu.html',q:'AVPU mental status'},motor_sensory:{label:'Stroke findings',sim:'/vitals/motor-sensory-assessment.html',q:'stroke assessment'},blood_glucose:{label:'Blood glucose',sim:'/vitals/bgl.html',q:'blood glucose hypoglycemia'},sample:{label:'SAMPLE history',sim:'/vitals/sample-history.html',q:'SAMPLE history'},chest_assessment:{label:'Chest assessment',sim:'/vitals/chest-assessment.html',q:'chest trauma assessment'},trauma_assessment:{label:'Rapid trauma assessment',sim:'/vitals/trauma-assessment.html',q:'rapid trauma assessment'},abdominal_assessment:{label:'Abdominal assessment',sim:'/vitals/abdominal-assessment.html',q:'abdominal assessment'},pediatric_assessment_triangle:{label:'Pediatric Assessment Triangle',sim:'/vitals/pediatric-assessment-triangle.html',q:'Pediatric Assessment Triangle'},clinical_impression:{label:'Clinical impression',sim:'/vitals/clinical-impression.html',q:'clinical impression differential diagnosis'},pcr_handoff:{label:'PCR and handoff',sim:'/vitals/pcr-handoff.html',q:'MIST handoff PCR documentation'}
};
const plans={
 asthma:{critical:['airway','breathing','respirations','spo2','breath_sounds'],expected:['airway','breathing','perfusion','pulse','blood_pressure','respirations','spo2','breath_sounds','sample','clinical_impression','pcr_handoff']},
 stroke:{critical:['airway','motor_sensory','blood_glucose','mental_status'],expected:['airway','breathing','perfusion','pulse','blood_pressure','respirations','spo2','mental_status','motor_sensory','blood_glucose','sample','clinical_impression','pcr_handoff']},
 hypoglycemia:{critical:['airway','mental_status','blood_glucose'],expected:['airway','breathing','perfusion','pulse','blood_pressure','respirations','spo2','mental_status','blood_glucose','sample','clinical_impression','pcr_handoff']},
 trauma:{critical:['airway','breathing','perfusion','chest_assessment','trauma_assessment'],expected:['airway','breathing','perfusion','pulse','blood_pressure','respirations','spo2','breath_sounds','chest_assessment','trauma_assessment','abdominal_assessment','pcr_handoff']},
 pediatric:{critical:['pediatric_assessment_triangle','airway','breathing','spo2','perfusion'],expected:['pediatric_assessment_triangle','airway','breathing','perfusion','pulse','blood_pressure','respirations','spo2','breath_sounds','sample','pcr_handoff']}
};
const plan=plans[caseId]||plans.asthma;
function finding(key){const f=record.findings||{};if(f[key])return f[key];const aliases={airway:['airway_assessment'],breathing:['breathing_assessment','breathing_quality'],perfusion:['perfusion_assessment','skin'],sample:['sample_history'],motor_sensory:['motor_sensory_assessment'],chest_assessment:['chest'],trauma_assessment:['trauma'],abdominal_assessment:['abdominal'],clinical_impression:['impression'],pcr_handoff:['handoff']};for(const alias of aliases[key]||[])if(f[alias])return f[alias];if(key==='sample'&&Object.keys(record.history||{}).length)return{value:'History recorded',recordedAt:record.updatedAt};if(key==='clinical_impression'&&record.impressions?.primary)return{value:record.impressions.primary,recordedAt:record.updatedAt};if(key==='pcr_handoff'&&(record.documentation?.handoff||record.documentation?.narrative))return{value:'Report prepared',recordedAt:record.updatedAt};return null}
function valueOf(f){return f?.finding||f?.value||f?.details||'Recorded'}
function simUrl(key){return `${catalog[key].sim}?mode=scenario&resume=1&case=${encodeURIComponent(caseId)}`}
function refUrl(key){return `/ems-encyclopedia.html?q=${encodeURIComponent(catalog[key].q)}&level=EMT&view=field&return=${encodeURIComponent(`/vitals/scenario-debrief.html?resume=1&case=${caseId}`)}`}
function item(kind,title,text,link,linkText='Review'){return `<article class="review-item ${kind}"><span class="icon">${kind==='good'?'✓':kind==='bad'?'!':'→'}</span><div><h3>${esc(title)}</h3><p>${esc(text)}</p></div>${link?`<a href="${link}">${linkText}</a>`:''}</article>`}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const criticalDone=plan.critical.filter(finding),expectedDone=plan.expected.filter(finding),missing=plan.expected.filter(k=>!finding(k));
const abnormal=Object.entries(record.findings||{}).filter(([,f])=>f?.normality==='not-normal'||f?.status==='abnormal');
const reportReady=!!finding('pcr_handoff');
let score=Math.round(((criticalDone.length/plan.critical.length)*45)+((expectedDone.length/plan.expected.length)*40)+(reportReady?15:0));
score=Math.max(0,Math.min(100,score));
$('scoreValue').textContent=`${score}%`;$('scoreRing').style.setProperty('--score',`${score}%`);
$('scoreLabel').textContent=score>=90?'Strong scenario performance':score>=75?'Generally ready with focused review':score>=55?'Developing assessment': 'Major assessment gaps remain';
$('scoreSummary').textContent=score>=90?'You identified the critical priorities and built a report-ready patient picture.':score>=75?'The patient picture is mostly complete. Review the remaining gaps before repeating the case.':score>=55?'Several useful findings were collected, but important priorities or report elements remain incomplete.':'Return to the guided assessment and complete the critical patient priorities before attempting the report.';
$('criticalMetric').textContent=`${criticalDone.length}/${plan.critical.length}`;$('findingMetric').textContent=`${expectedDone.length}/${plan.expected.length}`;$('abnormalMetric').textContent=String(abnormal.length);$('reportMetric').textContent=reportReady?'Ready':'Not ready';
$('priorityBadge').textContent=`${criticalDone.length}/${plan.critical.length}`;$('priorityBadge').className=`status-badge ${criticalDone.length===plan.critical.length?'good':criticalDone.length?'warn':'bad'}`;
$('priorityList').innerHTML=plan.critical.map(k=>{const f=finding(k);return f?item('good',catalog[k].label,`Completed: ${valueOf(f)}`,refUrl(k),'Reference'):item('bad',catalog[k].label,'This scenario priority has not been documented.',simUrl(k),'Complete')}).join('');
$('abnormalBadge').textContent=abnormal.length?`${abnormal.length} found`:'None recorded';$('abnormalBadge').className=`status-badge ${abnormal.length?'warn':''}`;
$('abnormalList').innerHTML=abnormal.length?abnormal.map(([k,f])=>item('warn',f.label||catalog[k]?.label||k.replaceAll('_',' '),valueOf(f),catalog[k]?refUrl(k):'',catalog[k]?'Explain':'' )).join(''):item('warn','No abnormal findings recorded','That may be correct only if the patient is normal. Recheck whether abnormal findings were obtained and classified.','','');
$('missingBadge').textContent=missing.length?`${missing.length} missing`:'Complete';$('missingBadge').className=`status-badge ${missing.length?'bad':'good'}`;
$('missingList').innerHTML=missing.length?missing.map(k=>item('bad',catalog[k].label,'Not present in the active patient record.',simUrl(k),'Complete')).join(''):item('good','Expected assessment complete','All expected findings for this scenario are represented in the patient record.','','');
const ordered=plan.expected.map(k=>({k,f:finding(k)})).filter(x=>x.f?.recordedAt).sort((a,b)=>new Date(a.f.recordedAt)-new Date(b.f.recordedAt));
const firstCriticalIndex=ordered.findIndex(x=>plan.critical.includes(x.k));const firstNonCriticalIndex=ordered.findIndex(x=>!plan.critical.includes(x.k));const sequenceGood=firstCriticalIndex!==-1&&(firstNonCriticalIndex===-1||firstCriticalIndex<=firstNonCriticalIndex);
const sequence=[];sequence.push(sequenceGood?item('good','Priority sequence','A critical patient priority was documented before lower-priority details.','',''):item('warn','Priority sequence','The record does not show a critical priority early. Begin with immediate threats before detailed history or documentation.','/vitals/visual-patient.html?resume=1','Return to Patient'));
sequence.push(reportReady?item('good','Handoff and PCR','A report is saved in the patient record.','/vitals/pcr-handoff.html?mode=scenario&resume=1','Review report'):item('bad','Handoff and PCR','The scenario does not yet have a saved verbal handoff or PCR narrative.','/vitals/pcr-handoff.html?mode=scenario&resume=1','Build report'));
sequence.push(record.impressions?.primary?item('good','Clinical impression',`Working impression: ${record.impressions.primary}`,refUrl('clinical_impression'),'Reference'):item('warn','Clinical impression','No working clinical impression is saved yet.',simUrl('clinical_impression'),'Complete'));
$('sequenceList').innerHTML=sequence.join('');$('sequenceBadge').textContent=reportReady&&sequenceGood?'Ready':'Review';$('sequenceBadge').className=`status-badge ${reportReady&&sequenceGood?'good':'warn'}`;
const remediation=[...new Set([...plan.critical.filter(k=>!finding(k)),...missing.filter(k=>!plan.critical.includes(k))])].slice(0,6);
$('remediationList').innerHTML=(remediation.length?remediation:['pcr_handoff']).map(k=>`<article class="remediation-item"><h3>${esc(catalog[k].label)}</h3><p>${finding(k)?'Strengthen your report and clinical explanation.':'Complete this missing component, then return to refresh the debrief.'}</p><div class="remediation-actions"><a href="${simUrl(k)}">Open simulator</a><a href="${refUrl(k)}">Quick reference</a></div></article>`).join('');
$('reflectionText').value=record.documentation?.debrief?.reflection||'';
$('saveDebrief').addEventListener('click',()=>{const reflection=$('reflectionText').value.trim();api.update(r=>{r.documentation=r.documentation||{};r.documentation.debrief={score,reflection,criticalComplete:criticalDone.length,criticalTotal:plan.critical.length,expectedComplete:expectedDone.length,expectedTotal:plan.expected.length,missing:[...missing],savedAt:new Date().toISOString()};return r});localStorage.setItem(`emscodesim_scenario_debrief_${caseId}`,JSON.stringify({score,reflection,savedAt:new Date().toISOString()}));$('saveStatus').textContent='Debrief saved to this patient record.';setTimeout(()=>$('saveStatus').textContent='',2800)});
$('refreshDebrief').addEventListener('click',()=>location.reload());
})();
